### ISSUE TITLE
Request failed - Status 400

### ISSUE THREAD

**Issue by Homey4Osty** [ugumba/homey-panasonic-comfort-cloud-alt#17]
Hello,
i don't have an access to the panasonic confort cloud with this app at the moment. I got this informations at the log file:

2024-06-26T11:25:54.563Z [err] [ManagerDrivers] [Driver:aircon] [Device:368553a9-1246-4c89-91bd-1cc4cb84fce2] getDevice failed: ServiceError: Request failed with status code 400
    at new ServiceError (/app/node_modules/panasonic-comfort-cloud-client/dist/src/model/ServiceError.js:23:28)
    at ComfortCloudClient.handleError (/app/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:184:15)
    at ComfortCloudClient.<anonymous> (/app/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:171:30)
    at step (/app/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:33:23)
    at Object.throw (/app/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:14:53)
    at rejected (/app/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  _code: undefined,
  _httpCode: 400
}
unhandledRejection:
ServiceError: Request failed with status code 400

Credentials are correkt ...

Can you fix it, please?

Thanks a lot.
Osty

**Comment by jarll** [comment]
There is already work in progress. See https://community.homey.app/t/app-pro-panasonic-comfort-cloud-alternative/75906

**Comment by ugumba** [comment]
Thanks for reporting, @Homey4Osty - this affects all users.

Panasonic has changed their authentication flow.  
This app relies on a JS package which handles this, you can follow the related issue here: 
https://github.com/marc2016/panasonic-comfort-cloud-client/issues/14

**Comment by Cannonb4ll** [comment]
Version 2.0.0 was released, that should solve it: https://www.npmjs.com/package/panasonic-comfort-cloud-client

**Comment by ugumba** [comment]
I've pushed 1.1.5 to _develop_ to consume the new pcc-client package.  
The token management/refreshing is now handled internally, so my own code could be simplified considerably.

I'm not on my home network, so have not been able to test at all!
Will probably be able to test tonight - adventurous souls are welcome to beat me to it. :smile:

**Comment by Homey4Osty** [comment]
Thanks for develop package ... but:
![image](https://github.com/ugumba/homey-panasonic-comfort-cloud-alt/assets/146454771/72048c71-78d5-4bec-9e0a-8a5c7c6ae43d)

I`m not able to install it... There's a time out...
What can i do?

**Comment by ugumba** [comment]
I think something similar happened the last time I installed (a couple of weeks back) - at least I got an error.  
Retrying worked fine for me.  I'll try 1.1.5 myself later this evening.

**Comment by ugumba** [comment]
Seems Panasonic bumped the API version from 1.20.1 to 1.21.0 - I've pushed an update to develop again.

**Comment by Cannonb4ll** [comment]
Seems to work again!

**Comment by Homey4Osty** [comment]
> I think something similar happened the last time I installed (a couple of weeks back) - at least I got an error.  
> Retrying worked fine for me.  I'll try 1.1.5 myself later this evening.

After the action 'npm audit fix' the installation was successful.

**Comment by ugumba** [comment]
Fix pushed to master
