### ISSUE TITLE
bad credentials, but...

### ISSUE THREAD

**Issue by mostlyflawles** [ugumba/homey-panasonic-comfort-cloud-alt#22]
I get "bad credentials" but I can login at https://accountglb.digital.panasonic.com with out any issues.
And https://accountglb.digital.panasonic.com seems to have MFA which I can't turn off.

Any idea what the issue might be? Does this app support MFA?

`2024-10-16T16:36:42.113Z [log] [MyApp] MyApp has been initialized
2024-10-16T16:36:45.276Z [log] [ManagerDrivers] [Driver:aircon] Driver has been initialized
2024-10-16T16:49:46.712Z [log] [ManagerDrivers] [Driver:aircon] settings.set
2024-10-16T16:49:46.762Z [log] [ManagerDrivers] [Driver:aircon] resetClient
2024-10-16T16:49:46.804Z [log] [ManagerDrivers] [Driver:aircon] settings.set
2024-10-16T16:49:46.816Z [log] [ManagerDrivers] [Driver:aircon] resetClient
2024-10-16T16:50:35.237Z [log] [ManagerDrivers] [Driver:aircon] onPairListDevices
2024-10-16T16:50:45.624Z [log] [ManagerDrivers] [Driver:aircon] initializing client (1.21.1)
2024-10-16T16:50:45.692Z [log] [ManagerDrivers] [Driver:aircon] authenticating me[dot]the[at]world.com
2024-10-16T16:50:52.829Z [err] [ManagerDrivers] [Driver:aircon] login failed: Error: code is null.
    at OAuthClient.oAuthProcess (/node_modules/panasonic-comfort-cloud-client/dist/src/OAuthClient.js:66:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ComfortCloudClient.login (/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:61:27)
    at async MyDriver.getClient (/drivers/aircon/driver.js:84:17)
    at async MyDriver.invokeClient (/drivers/aircon/driver.js:100:26)
    at async MyDriver.onPairListDevices (/drivers/aircon/driver.js:172:24)
2024-10-16T16:50:52.884Z [err] [ManagerDrivers] [Driver:aircon] bad credentials
2024-10-16T17:01:31.069Z [log] [ManagerDrivers] [Driver:aircon] settings.set
2024-10-16T17:01:31.116Z [log] [ManagerDrivers] [Driver:aircon] resetClient
2024-10-16T17:02:59.090Z [log] [ManagerDrivers] [Driver:aircon] onPairListDevices
2024-10-16T17:02:59.526Z [log] [ManagerDrivers] [Driver:aircon] initializing client (1.21.1)
2024-10-16T17:02:59.543Z [log] [ManagerDrivers] [Driver:aircon] authenticating  me[dot]the[at]world.com
2024-10-16T17:03:01.469Z [err] [ManagerDrivers] [Driver:aircon] login failed: ServiceError: Request failed with status code 401
statusCode=401,code=Unauthorized,msg=Login ID or password is incorrect.
    at ComfortCloudClient.handleError (/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:147:31)
    at ComfortCloudClient.login (/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:66:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MyDriver.getClient (/drivers/aircon/driver.js:84:17)
    at async MyDriver.invokeClient (/drivers/aircon/driver.js:100:26)
    at async MyDriver.onPairListDevices (/drivers/aircon/driver.js:172:24) {
  _code: 'invalid_user_password',
  _httpCode: -1
}
2024-10-16T17:03:01.519Z [err] [ManagerDrivers] [Driver:aircon] bad credentials
`

**Comment by ugumba** [comment]
Not sure what happens in your case - both the Homey app and the web site works as expected for me, using the exact same credentials.

The client package used by the app to authenticate was updated earlier this year to support Panasonic's new auth flow - which is more secure, but doesn't require MFA. I assume you're using the current version from the GitHub repo?

I'm sure you've made sure to type/paste the password correctly (no trailing space, for example)?

**Comment by ugumba** [comment]
Hmm, I just realized I didn't need 2FA to sign in to the web page. I don't really want to click the "reset MFA" link...

**Comment by mostlyflawles** [comment]
Set up the login method
![Screenshot_1](https://github.com/user-attachments/assets/cbcce351-43d4-4d3a-93d9-ccbbfeab7318)
Reset two-factor...
![Screenshot_2](https://github.com/user-attachments/assets/ab864122-3cb9-4bf5-8449-c82ec911ee3b)

PW - Yes, I tried again and i'm quite sure I got it right.
Clarification, I just got my Panasonic so this is a first time setup.

**Comment by ugumba** [comment]
Have you logged in with these credentials in the Panasonic Comfort Cloud mobile app (Apple or Android)?

There are terms & conditions that need to be accepted before the account is authorized to do anything.
I've only seen these T&C in the mobile app (and the Homey app wouldn't know how to present them).
________________________________

**Comment by mostlyflawles** [comment]
Yes, I have, but.. it might be that I initiated it by using a google-SSO, later on I changed it to "only-email" .
So now I've logged out and in the app (did not have to accept any T&C) and retested this in the Homey app, the issue remains.

**Comment by Magnusri** [comment]
Adding to this to maybe help you out;

Other Panasonic Comfort Cloud integrations say these things:
"_Before installing this integration, you must have completed the 2FA process using the Panasonic Comfort Cloud app._"
"_The authentication process can be fiddly and may require resetting the MFA by logging in / out from the Panasonic app._"

**Comment by ugumba** [comment]
@mostlyflawles, please try the latest version (1.1.14), and open a new issue if the problem remains.
