### ISSUE TITLE
Login issue - works fine until this error

### ISSUE THREAD

**Issue by ronnie2113** [ugumba/homey-panasonic-comfort-cloud-alt#23]
Tested login here: https://accountglb.digital.panasonic.com/ and on the app, no issues only in Homey app.
App has been restarted and disabled and enabled again.

2024-11-05T06:29:40.373Z [log] [MyApp] MyApp has been initialized
2024-11-05T06:29:41.034Z [log] [ManagerDrivers] [Driver:aircon] Driver has been initialized
2024-11-05T06:29:41.319Z [log] [ManagerDrivers] [Driver:aircon] initializing client (1.22.0)
2024-11-05T06:29:41.328Z [log] [ManagerDrivers] [Driver:aircon] authenticating ronnie[dot]skau.pedersen[at]gmail.com
2024-11-05T06:29:49.122Z [err] [ManagerDrivers] [Driver:aircon] login failed: ServiceError: Request failed with status code 412
Precondition Failed
    at ComfortCloudClient.handleError (/app/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:147:31)
    at ComfortCloudClient.login (/app/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:66:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MyDriver.getClient (/app/drivers/aircon/driver.js:84:17)
    at async MyDriver.invokeClient (/app/drivers/aircon/driver.js:100:26)
    at async MyDevice.fetchFromService (/app/drivers/aircon/device.js:32:22)
    at async MyDevice.fetchAndRestartTimer (/app/drivers/aircon/device.js:58:9)
    at async MyDevice.onInit (/app/drivers/aircon/device.js:126:13)
    at async MyDevice._onInit (/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js:148:7) {
  _code: 41201,
  _httpCode: -1
}
2024-11-05T06:29:49.131Z [err] [ManagerDrivers] [Driver:aircon] bad credentials
2024-11-05T06:29:49.133Z [err] [ManagerDrivers] [Driver:aircon] [Device:4945959c-5e31-42b4-a443-0a806f8be858] getDevice failed: Error: Authentication failed, edit credentials in app settings.
    at MyDriver.getClient (/app/drivers/aircon/driver.js:94:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MyDriver.invokeClient (/app/drivers/aircon/driver.js:100:26)
    at async MyDevice.fetchFromService (/app/drivers/aircon/device.js:32:22)
    at async MyDevice.fetchAndRestartTimer (/app/drivers/aircon/device.js:58:9)
    at async MyDevice.onInit (/app/drivers/aircon/device.js:126:13)
    at async MyDevice._onInit (/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js:148:7)
2024-11-05T06:29:49.150Z [log] [ManagerDrivers] [Driver:aircon] [Device:4945959c-5e31-42b4-a443-0a806f8be858] Device 'CS-HZ25XKE+4891758308' has been initialized

**Comment by ugumba** [comment]
Yes, I see the same thing since this morning.

**Comment by ronnie2113** [comment]
Typical Panasonic ;-) 
They had login issues in their app for years before fixing it! 
Let me know if you need some testing.

**Comment by ronnie2113** [comment]
For your information, I just read on a Facebook site that others have the issue and that Panasonic has changed their API. 
Don't if that is helpful :-)

**Comment by ugumba** [comment]
The upstream client package has the fix already, so try it out!  Hopefully, this will last a while.
