### ISSUE TITLE
Seems I can't log in to Cloud service (follow up on earlier issue)

### ISSUE THREAD

**Issue by mostlyflawles** [ugumba/homey-panasonic-comfort-cloud-alt#32]
Regards to
https://github.com/ugumba/homey-panasonic-comfort-cloud-alt/issues/22

I've installaed 1.1.14
I've logged out from the Andriod app
I've reset MFA at https://accountglb.digital.panasonic.com/
I've entered the credentials in the app
I've added the device successfully

Then I get...
    Request failed with status code 500
    Adapter Communication error

	
```
	
	T11:07:44.992Z [log] [MyApp] MyApp has been initialized
2024-12-28T11:08:27.639Z [log] [ManagerDrivers] [Driver:aircon] Driver has been initialized
2024-12-28T11:10:30.836Z [log] [ManagerDrivers] [Driver:aircon] settings.set
2024-12-28T11:10:30.889Z [log] [ManagerDrivers] [Driver:aircon] resetClient
2024-12-28T11:10:30.933Z [log] [ManagerDrivers] [Driver:aircon] settings.set
2024-12-28T11:10:30.950Z [log] [ManagerDrivers] [Driver:aircon] resetClient
2024-12-28T11:11:25.494Z [log] [ManagerDrivers] [Driver:aircon] onPairListDevices
2024-12-28T11:11:27.293Z [log] [ManagerDrivers] [Driver:aircon] initializing client (1.22.0)
2024-12-28T11:11:27.323Z [log] [ManagerDrivers] [Driver:aircon] authenticating no[dot]no[at]no.com
2024-12-28T11:11:31.851Z [log] [ManagerDrivers] [Driver:aircon] authenticated
2024-12-28T11:11:32.337Z [log] [ManagerDrivers] [Driver:aircon] [
  {
    name: 'My House: Vardagsrum',
    data: { id: 'CS-NZ25YKE-1+no' }
  }
]
2024-12-28T11:11:57.993Z [err] [ManagerDrivers] [Driver:aircon] [Device:7bdaa27f-26e0-40d8-bb32-14842171bb89] getDevice failed: AdapterCommunicationError [ServiceError]: Request failed with status code 500
Adapter Communication error
    at ComfortCloudClient.handleError (/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:155:31)
    at ComfortCloudClient.getDevice (/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:140:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /drivers/aircon/device.js:69:30
    at async MyDriver.invokeClient (/drivers/aircon/driver.js:86:24)
    at async MyDevice.fetchFromService (/drivers/aircon/device.js:68:22)
    at async MyDevice.fetchAndRestartTimer (/drivers/aircon/device.js:100:9)
    at async MyDevice.onInit (/drivers/aircon/device.js:173:13)
    at async MyDevice._onInit (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js:1:1682) {
  _code: 5005,
  _httpCode: 500
}
2024-12-28T11:12:03.618Z [log] [ManagerDrivers] [Driver:aircon] [Device:7bdaa27f-26e0-40d8-bb32-14842171bb89] Device 'CS-NZ25YKE-1+no' has been initialized
2024-12-28T11:12:04.735Z [log] [ManagerDrivers] [Driver:aircon] [Device:7bdaa27f-26e0-40d8-bb32-14842171bb89] Device has been added
2024-12-28T11:12:07.739Z [log] [ManagerDrivers] [Driver:aircon] [Device:7bdaa27f-26e0-40d8-bb32-14842171bb89] postToService: { onoff: false }
2024-12-28T11:12:08.946Z [err] [ManagerDrivers] [Driver:aircon] [Device:7bdaa27f-26e0-40d8-bb32-14842171bb89] setParameters failed: AdapterCommunicationError [ServiceError]: Request failed with status code 500
Adapter Communication error
    at ComfortCloudClient.handleError (/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:155:31)
    at ComfortCloudClient.setParameters (/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:183:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MyDriver.invokeClient (/drivers/aircon/driver.js:86:24)
    at async MyDevice.postToService (/drivers/aircon/device.js:122:13)
    at async Timeout.n [as _onTimeout] (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js:1:7566) {
  _code: 5005,
  _httpCode: 500
}
2024-12-28T11:51:51.922Z [log] [ManagerDrivers] [Driver:aircon] [Device:7bdaa27f-26e0-40d8-bb32-14842171bb89] postToService: { operation_mode: 'Auto' }
2024-12-28T11:52:14.834Z [err] [ManagerDrivers] [Driver:aircon] [Device:7bdaa27f-26e0-40d8-bb32-14842171bb89] setParameters failed: AdapterCommunicationError [ServiceError]: Request failed with status code 500
Adapter Communication error
    at ComfortCloudClient.handleError (/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:155:31)
    at ComfortCloudClient.setParameters (/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:183:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MyDriver.invokeClient (/drivers/aircon/driver.js:86:24)
    at async MyDevice.postToService (/drivers/aircon/device.js:122:13)
    at async Timeout.n [as _onTimeout] (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js:1:7566) {
  _code: 5005,
  _httpCode: 500
}
2024-12-28T11:52:27.026Z [log] [ManagerDrivers] [Driver:aircon] [Device:7bdaa27f-26e0-40d8-bb32-14842171bb89] Device 'CS-NZ25YKE-1+no' has been deleted
2024-12-28T12:00:46.479Z [log] [ManagerDrivers] [Driver:aircon] onPairListDevices
2024-12-28T12:00:47.989Z [log] [ManagerDrivers] [Driver:aircon] [
  {
    name: 'My House: Vardagsrum',
    data: { id: 'CS-NZ25YKE-1+no' }
  }
]
2024-12-28T12:00:52.613Z [err] [ManagerDrivers] [Driver:aircon] [Device:bb125bb6-a6f8-41c2-972c-498c50d974bd] getDevice failed: AdapterCommunicationError [ServiceError]: Request failed with status code 500
Adapter Communication error
    at ComfortCloudClient.handleError (/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:155:31)
    at ComfortCloudClient.getDevice (/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:140:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /drivers/aircon/device.js:69:30
    at async MyDriver.invokeClient (/drivers/aircon/driver.js:86:24)
    at async MyDevice.fetchFromService (/drivers/aircon/device.js:68:22)
    at async MyDevice.fetchAndRestartTimer (/drivers/aircon/device.js:100:9)
    at async MyDevice.onInit (/drivers/aircon/device.js:173:13)
    at async MyDevice._onInit (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js:1:1682) {
  _code: 5005,
  _httpCode: 500
}
2024-12-28T12:00:52.712Z [log] [ManagerFlow] [FlowCardAction][change-air-swing-updown] Warning: Run listener was already registered.
2024-12-28T12:00:52.732Z [log] [ManagerFlow] [FlowCardAction][change-air-swing-leftright] Warning: Run listener was already registered.
2024-12-28T12:00:52.746Z [log] [ManagerFlow] [FlowCardAction][change-operation-mode] Warning: Run listener was already registered.
2024-12-28T12:00:52.759Z [log] [ManagerFlow] [FlowCardAction][change-fan-speed] Warning: Run listener was already registered.
2024-12-28T12:00:52.774Z [log] [ManagerFlow] [FlowCardAction][change-eco-mode] Warning: Run listener was already registered.
2024-12-28T12:00:52.803Z [log] [ManagerDrivers] [Driver:aircon] [Device:bb125bb6-a6f8-41c2-972c-498c50d974bd] Device 'CS-NZ25YKE-1+no' has been initialized
2024-12-28T12:00:52.851Z [log] [ManagerDrivers] [Driver:aircon] [Device:bb125bb6-a6f8-41c2-972c-498c50d974bd] Device has been added
2024-12-28T12:04:30.366Z [log] [ManagerDrivers] [Driver:aircon] [Device:bb125bb6-a6f8-41c2-972c-498c50d974bd] Device 'CS-NZ25YKE-1+no' was renamed to 'My House: Vardagsrum'
2024-12-28T12:04:33.242Z [log] [ManagerDrivers] [Driver:aircon] [Device:bb125bb6-a6f8-41c2-972c-498c50d974bd] Device 'CS-NZ25YKE-1+no' has been deleted
2024-12-28T12:06:14.026Z [log] [ManagerDrivers] [Driver:aircon] onPairListDevices
2024-12-28T12:06:17.927Z [log] [ManagerDrivers] [Driver:aircon] [
  {
    name: 'My House: Vardagsrum',
    data: { id: 'CS-NZ25YKE-1+no' }
  }
]
2024-12-28T12:06:23.315Z [err] [ManagerDrivers] [Driver:aircon] [Device:808487db-cad5-4dad-affb-caf58a36f138] getDevice failed: AdapterCommunicationError [ServiceError]: Request failed with status code 500
Adapter Communication error
    at ComfortCloudClient.handleError (/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:155:31)
    at ComfortCloudClient.getDevice (/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:140:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /drivers/aircon/device.js:69:30
    at async MyDriver.invokeClient (/drivers/aircon/driver.js:86:24)
    at async MyDevice.fetchFromService (/drivers/aircon/device.js:68:22)
    at async MyDevice.fetchAndRestartTimer (/drivers/aircon/device.js:100:9)
    at async MyDevice.onInit (/drivers/aircon/device.js:173:13)
    at async MyDevice._onInit (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js:1:1682) {
  _code: 5005,
  _httpCode: 500
}
2024-12-28T12:06:23.631Z [log] [ManagerFlow] [FlowCardAction][change-air-swing-updown] Warning: Run listener was already registered.
2024-12-28T12:06:23.835Z [log] [ManagerFlow] [FlowCardAction][change-air-swing-leftright] Warning: Run listener was already registered.
2024-12-28T12:06:23.851Z [log] [ManagerFlow] [FlowCardAction][change-operation-mode] Warning: Run listener was already registered.
2024-12-28T12:06:23.868Z [log] [ManagerFlow] [FlowCardAction][change-fan-speed] Warning: Run listener was already registered.
2024-12-28T12:06:23.885Z [log] [ManagerFlow] [FlowCardAction][change-eco-mode] Warning: Run listener was already registered.
2024-12-28T12:06:23.921Z [log] [ManagerDrivers] [Driver:aircon] [Device:808487db-cad5-4dad-affb-caf58a36f138] Device 'CS-NZ25YKE-1+no' has been initialized
2024-12-28T12:06:23.938Z [log] [ManagerDrivers] [Driver:aircon] [Device:808487db-cad5-4dad-affb-caf58a36f138] Device has been added

```

**Comment by ugumba** [comment]
I'm sorry, I'm unable to provide much assistance here.

The 500 error is returned from the Panasonic web service, so "Adapter Communication error" probably indicates that the web service is unable to communicate with the Wifi adapter in your heat pump.  This is outside the scope of the app, and I can only guess, since there's no documentation for the web service API.

I assume the Android app works fine for you?

**Comment by Magnusri** [comment]
I do not know if this addresses the issue correctly, but it is the same problem:
https://github.com/sockless-coding/panasonic_cc/issues/339#issuecomment-2466464789

Does it work sometimes? / If you keep the app running despite the errors, does it sometimes collect data? (Do you get any graphs for temperatures and such?)

**Comment by mostlyflawles** [comment]
Yes, the heater didn't have connection to the wifi. It's now solved and 1.1.14 works great.
Unfortunately these issues (wifi and earlier version of this app) overlapped each other so I overlooked this, sorry for that.

This can be closed.
